# Memory-efficient debug configuration for quick experimentation
# Minimal BERT fine-tuning for reduced memory usage

# Experiment settings
experiment_dir: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/experiments"

# Model configuration - Memory optimized
model:
  bert_model: "google-bert/bert-base-uncased"
  text_embedding_dim: 768
  bert_finetune_strategy: "minimal"  # Only fine-tune last 2 layers + projection (saves ~80% memory)
  latent_dim: 8
  pretrained_model_name: "runwayml/stable-diffusion-v1-5"
  cross_attention_dim: 768
  attention_head_dim: 8
  use_flash_attention: true
  freeze_encoder: true
  freeze_decoder: true
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# Data configuration - Optimized for speed and memory
data:
  csv_path: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/data/text_description_concat.csv"
  image_dir: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/data/small_images"
  batch_size: 8               # Reduced batch size for memory efficiency
  image_size: 215
  num_workers: 4              # Reduced workers to save memory
  pin_memory: true
  val_split: 0.15
  test_split: 0.05

# Training configuration - Ultra fast
training:
  vae_epochs: 50              # Very short for debugging
  diffusion_epochs: 50
  final_epochs: 20
  
  # Fast KL annealing
  kl_anneal_start: 0
  kl_anneal_end: 3            # Very fast annealing
  kl_weight_start: 0.0
  kl_weight_end: 0.01         # Very low KL weight
  free_bits: 0.1              # Minimal free bits
  
  # Minimal loss weights for speed
  reconstruction_weight: 1.0
  perceptual_weight: 0.01     # Minimal perceptual loss for speed
  kl_weight: 0.001            # Minimal KL weight
  
  # More frequent logging for debugging
  log_every: 5
  save_every: 20
  sample_every: 15

# Optimization - Memory efficient
optimization:
  optimizer: "adamw"
  learning_rate: 0.0003       # Slightly higher for faster convergence
  text_encoder_lr: 0.0001     # Higher text encoder LR (can be higher since we're only training 2 layers)
  weight_decay: 0.01
  max_grad_norm: 1.0
  use_mixed_precision: false  # Keep false for MPS stability
  scheduler: "constant"

device: "mps"
