# Configuration for training the Pokemon sprite generator

# Model configuration
model:
  text_encoder:
    model_name: "prajjwal1/bert-mini"
    nhead: 4
    num_encoder_layers: 2
    hidden_dim: 256
    dropout: 0.1
  
  decoder:
    text_embedding_dim: 256
    noise_dim: 100
    final_image_channels: 3
  attention:
    encoder_dim: 256
    decoder_dim: 256

# Training configuration
training:
  batch_size: 16
  num_epochs: 5
  learning_rate: 0.0002
  beta1: 0.5
  beta2: 0.999
  weight_decay: 0.0001
  
  # Loss weights
  reconstruction_weight: 1.0
  attention_weight: 0.1
  
  # Checkpoints
  save_every: 10
  checkpoint_dir: "checkpoints"
  
  # Logging
  log_every: 100
  log_dir: "logs"

# Data configuration
data:
  dataset_url: "https://github.com/cristobalmitchell/pokedex/"
  data_dir: "data"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  
# Device
device: "mps"  # or "cpu"