# Configuration for training the Pokemon sprite generator with VAE architecture

# Experiment settings
experiment_dir: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/experiments"

# Model configuration
model:
  bert_model: "prajjwal1/bert-mini"
  text_embedding_dim: 256
  noise_dim: 100
  latent_dim: 512
  nhead: 4
  num_encoder_layers: 2

# Data configuration
data:
  csv_path: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/data/pokemon.csv"
  image_dir: "/Users/gabrieleconte/Developer/pokemon-sprite-generator/data/small_images"
  batch_size: 16
  image_size: 215
  num_workers: 8
  pin_memory: true
  train_split: 0.8
  val_split: 0.15
  test_split: 0.05

# Training configuration
training:
  max_epochs: 100
  
  # Two-stage training
  phase1_epochs: 50  # Train only text encoder for first 50 epochs
  
  # Loss weights
  reconstruction_weight: 1.0
  attention_weight: 0.1
  
  # KL annealing to prevent posterior collapse
  kl_anneal_start: 0      # Start KL annealing from epoch 0
  kl_anneal_end: 30       # End KL annealing at epoch 30
  kl_weight_start: 0.0    # Start with no KL weight
  kl_weight_end: 0.5      # End with moderate KL weight
  free_bits: 0.5          # Minimum KL bits per dimension
  
  # Gradient clipping
  grad_clip: 1.0
  
  # Checkpoints
  save_every: 10
  checkpoint_dir: "checkpoints"
  
  # Logging
  log_every: 50
  log_dir: "logs"
  
  # Sampling
  sample_every: 5

# Optimization
optimization:
  optimizer: "adamw"
  learning_rate: 0.0002
  text_encoder_lr: 0.0001  # Lower LR for text encoder fine-tuning
  vae_decoder_lr: 0.0001   # Lower LR for VAE decoder fine-tuning
  beta1: 0.5
  beta2: 0.999
  weight_decay: 0.0001
  grad_clip: 1.0
  scheduler: "cosine"
  max_epochs: 100
  step_size: 30
  gamma: 0.1
  patience: 10

# Logging and monitoring
logging:
  log_interval: 50
  sample_interval: 5
  checkpoint_interval: 10
  
# Device
device: "mps"  # or "cpu"